### PR TITLE
Jaxfry easy setup

### PR DESCRIPTION
**Pull request by jaxfry**
Allows for an easy setup and no WSL needed. (testing right now if it works). Removed webbrowser from requirements as it is included with python. replaced using the windows api to play sound with pysound. added easy option to disable tuya.

### CODE REVIEW

**Comment by DogeLord081** [comment]
This is great, but vits does not work on windows because of the dependency pyopenjtalk which is nearly impossible, at least for me, to install on windows. I have a new very easy tts engine for vits that doesnt require wsl and is realtime and easy to install so i will hold off on this until i release the new version and then i will review it again or request some changes to the vits install. Thanks

**Comment by jaxfry** [comment]
mk! Np!

**Comment by DogeLord081** [comment]
I was in class when I messaged that but now that I got a good look at it, setup.py is actually amazing. I wanted to make something like that, but all I wanted to do was keep updating and updating the AI and I didn't really get around to doing it but yea I'll commit the new version soon and we just gotta change a few tiny things in setup.py and it should be even easier now to install bc the TTS is super simple

**Comment by DogeLord081** [comment]
Ok so here are the major changes for the new prerelease I just published:
- OneRealityENMemory.py was renamed to just OneRealityMemory.py
- The whole WSL command thing was replaced by one line in line 311
- The VITS .env variables are gone
- New requirements
- My fork of vits-simple-api is included as a submodule now in the repo
- OneReality.bat starts my vits-simple-api fork first before starting the actual OneReality program

Also, can you make the install script automatically download G_latest.pth into vits-simple-api/Model/g/ from huggingface https://huggingface.co/DogeLord/megumin-VITS/tree/main? Thanks

**Pull request merged**
